# Generated by Django 4.2.2 on 2023-06-06 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("GLSApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Submenu",
            fields=[
                ("subMenuId", models.AutoField(primary_key=True, serialize=False)),
                ("menuTitle", models.CharField(max_length=50)),
                ("menuSequence", models.IntegerField()),
                (
                    "menuId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="GLSApp.menumaster",
                    ),
                ),
            ],
            options={
                "ordering": ["menuSequence"],
            },
        ),
    ]
