# Generated by Django 4.2.2 on 2023-06-08 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("GLSApp", "0003_rename_menuid_submenu_menuid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coursemaster",
            fields=[
                ("courseId", models.AutoField(primary_key=True, serialize=False)),
                ("courseName", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name="submenu",
            options={},
        ),
        migrations.CreateModel(
            name="Pagemaster",
            fields=[
                ("pageId", models.AutoField(primary_key=True, serialize=False)),
                ("pageName", models.CharField(max_length=50)),
                ("pageContent", models.CharField(max_length=2000)),
                (
                    "courseId",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="GLSApp.coursemaster",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="submenu",
            name="pageId",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="GLSApp.pagemaster",
            ),
        ),
    ]
