# Generated by Django 4.1.4 on 2023-06-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GLSApp', '0004_coursemaster_alter_submenu_options_pagemaster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagemaster',
            name='pageContent',
            field=models.TextField(),
        ),
    ]
