# Generated by Django 4.2.1 on 2023-06-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GLSApp', '0005_alter_pagemaster_pagecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activitytype',
            fields=[
                ('activityId', models.AutoField(primary_key=True, serialize=False)),
                ('activityName', models.CharField(max_length=50)),
            ],
        ),
    ]
